config/routes.rb
Rails.application.routes.draw do
  resources :carros
  resources :users
  resources :addresses
  resources :actors
  get 'actors/index'

  get 'actors/show'

  get 'actors/create'

  get 'actors/update'

  get 'actors/destroy'

  resources :movies

  resources :movies
  root 'payers#index'
  resources :payers

  resources :tasks

  get 'verification_autocomplete/.:format' => 'routes#test_action'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/carro.rb
class Carro < ActiveRecord::Base
end

app/models/interface_log.rb
class InterfaceLog < ActiveRecord::Base
    belongs_to :patient_master, autosave: true

  # attr_accessible :response_message, #formerly known as :content_file
  #                 :response_code,
  #                 :response_timestamp,
  #                 :vendor_account,
  #                 :vendor_id,
  #                 :vendor_name,
  #                 :vendor_type,
  #                 :patient_master_id,
  #                 :patient_master_uuid,
  #                 :user_full_name,
  #                 :user_id,
  #                 :log   # Paperclip

  def log_entry(log={})

    self.patient_master_id =    log[:p_master_id]
    self.response_message  =    log[:r_message]
    self.response_code =        log[:r_code]
    self.response_timestamp =   log[:r_timestamp]
    self.vendor_account =       log[:v_account]
    self.vendor_id =            log[:v_id]
    self.vendor_name =          log[:v_name]
    self.patient_master_uuid =  log[:p_master_uuid]
    self.user_full_name =       log[:u_full_name]
    self.user_id =              log[:u_id]

    puts log
    self.save
  end
end

=begin
{
 :patient_master_id=>10,
 :response_message=>"El mensajito",
 :response_code=>"201",
 :response_timestamp=>"20160511",
 :vendor_account=>"909090909",
 :vendor_id=>"223344",
 :vendor_name=>"CMD Orlando",
 :vendor_type=>"collaborate_md",
 :patient_master_uuid=>"e02aa3de-1f3b-4083-9f26-5532522b5d81",
 :user_full_name=>"Angel Huezo",
 :user_id=>"1"
 }

 {
 :p_master_id=>10, :r_message=>"El mensajito", :r_code=>"201", :r_timestamp=>"20160511",
 :v_account=>"909090909", :v_id=>"223344", :v_name=>"CMD Orlando", :v_type=>"collaborate_md",
 :p_master_uuid=>"e02aa3de-1f3b-4083-9f26-5532522b5d81", :u_full_name=>"Angel Huezo", :u_id=>"1"
 }
=end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :region
  has_many :people

  def self.in_region(region)

    # joins(:region).merge(Region.where('regions.name = ?', region))
    joins(:region).where(regions: {name: region}) #same as above, but clearer

  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/models/payer.rb
class Payer < ActiveRecord::Base
   # attr_accessible :kipu_insurance_id, :payer_name,
                  # :payer_synonym, :api_payer_id,
                  # :provider_id, :type  - need to add to migration


  def self.import
      update_folder = 'db/update_files/'
      import_file   = Rails.root.join(update_folder,'payers_test.json')
      records       = JSON.parse(File.read(import_file))

      fields = {}

      records.each do |payer|
        payer['PayerSynonyms'].each do |synonym|
          fields[:kipu_insurance_id] = payer['Id']
          fields[:api_payer_id]      = payer['ApiPayerId']
          fields[:payer_name]        = payer['HealthPlanName']
          fields[:payer_synonym]     = synonym['Name']
          # puts fields
          Payer.create(fields)
        end
      end
      puts 'Import Complete'



  end
end

app/models/payers_list.rb
class PayersList < ActiveRecord::Base

  # attr_accessible :kipu_insurance_id, :payer_name,
                  # :payer_synonym, :api_payer_id,
                  # :provider_id, :type  - need to add to migration


  def self.import
      update_folder = 'db/update_files/'
      import_file   = Rails.root.join(update_folder,'payers_2016-03-10.json')
      records       = JSON.parse(File.read(import_file))

      fields = {}

      records.each do |payer|
        payer['PayerSynonyms'].each do |synonym|
          fields[:kipu_insurance_id] = payer['Id']
          fields[:api_payer_id]      = payer['ApiPayerId']
          fields[:payer_name]        = payer['HealthPlanName']
          fields[:payer_synonym]     = synonym['Name']
          # puts fields
          PayersList.create(fields)
        end
      end
      puts 'Import Complete'



  end
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :location
  belongs_to :role
  belongs_to :manager, class_name: "Person", foreign_key: :manager_id
  has_many :employees, class_name: "Person", foreign_key: :manager_id

  def self.in_region(region)
    joins(:location).merge( Location.joins(:region).
                     where(regions: {name: region}) )
  end

  def self.alphabetically_by_region_and_location
    joins(:location).merge( Location.joins(:region)).
            order('regions.name, locations.name, people.name' )
  end
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :locations

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_one :collaborate_md_interface,  dependent: :destroy

  # attr_accessible  :company_name,  :vendor_status,  :vendor_type,
  # only necessary in Rails 3 - like Healthmatters.  'whitelis'


end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:name, :movie)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :all_tasks, only: [:index, :create]
  respond_to :html, :js

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
  end

  private

    def all_tasks
      @tasks = Task.all
    end

    def task_params
      params.require(:task).permit(:description, :deadline)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carros_helper.rb
module CarrosHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/payers_helper.rb
module PayersHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actors/_form.html.erb
<script type="text/javascript">
  $(function(){
    $('#actor_movie').autocomplete({
      minLength: 1,
      source: '<%= movies_path(:json) %>',
      focus: function(event, ui){
        $('#actor_movie').val(ui.item.title);
        console.log("Focus: ", ui.item.title);
        return false;
      },
      select: function(event, ui){
        $('#actor_movie').val(ui.item.title).effect("highlight", {}, 750);
        console.log("select: ", ui.item.title)
        return false;
      }
    })
    .data("autocomplete")._renderItem = function( ul, item ){
      return $("<li></li>").data("item.autocomplete", item)
      .append( "<a>" + item.title + "</a>" ).appendTo( ul );
    };
  });
</script>


<%= form_for(@actor) do |f| %>
  <% if @actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% @actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :movie %><br>
    <%= f.text_field :movie %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing Actor</h1>

<%= render 'form' %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Actors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Movie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
        <td><%= actor.movie %></td>
        <td><%= link_to 'Show', actor %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actor', new_actor_path %>

app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= render 'form' %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @actor.name %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @actor.movie %>
</p>

<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>