config/routes.rb
Rails.application.routes.draw do
  resources :carros
  resources :users
  resources :addresses
  resources :actors
  get 'actors/index'

  get 'actors/show'

  get 'actors/create'

  get 'actors/update'

  get 'actors/destroy'

  resources :movies

  resources :movies
  root 'payers#index'
  resources :payers

  resources :tasks

  get 'verification_autocomplete/.:format' => 'routes#test_action'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/carro.rb
class Carro < ActiveRecord::Base
end

app/models/interface_log.rb
class InterfaceLog < ActiveRecord::Base
    belongs_to :patient_master, autosave: true

  # attr_accessible :response_message, #formerly known as :content_file
  #                 :response_code,
  #                 :response_timestamp,
  #                 :vendor_account,
  #                 :vendor_id,
  #                 :vendor_name,
  #                 :vendor_type,
  #                 :patient_master_id,
  #                 :patient_master_uuid,
  #                 :user_full_name,
  #                 :user_id,
  #                 :log   # Paperclip

  def log_entry(log={})

    self.patient_master_id =    log[:p_master_id]
    self.response_message  =    log[:r_message]
    self.response_code =        log[:r_code]
    self.response_timestamp =   log[:r_timestamp]
    self.vendor_account =       log[:v_account]
    self.vendor_id =            log[:v_id]
    self.vendor_name =          log[:v_name]
    self.patient_master_uuid =  log[:p_master_uuid]
    self.user_full_name =       log[:u_full_name]
    self.user_id =              log[:u_id]

    puts log
    self.save
  end
end

=begin
{
 :patient_master_id=>10,
 :response_message=>"El mensajito",
 :response_code=>"201",
 :response_timestamp=>"20160511",
 :vendor_account=>"909090909",
 :vendor_id=>"223344",
 :vendor_name=>"CMD Orlando",
 :vendor_type=>"collaborate_md",
 :patient_master_uuid=>"e02aa3de-1f3b-4083-9f26-5532522b5d81",
 :user_full_name=>"Angel Huezo",
 :user_id=>"1"
 }

 {
 :p_master_id=>10, :r_message=>"El mensajito", :r_code=>"201", :r_timestamp=>"20160511",
 :v_account=>"909090909", :v_id=>"223344", :v_name=>"CMD Orlando", :v_type=>"collaborate_md",
 :p_master_uuid=>"e02aa3de-1f3b-4083-9f26-5532522b5d81", :u_full_name=>"Angel Huezo", :u_id=>"1"
 }
=end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :region
  has_many :people

  def self.in_region(region)

    # joins(:region).merge(Region.where('regions.name = ?', region))
    joins(:region).where(regions: {name: region}) #same as above, but clearer

  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/models/payer.rb
class Payer < ActiveRecord::Base
   # attr_accessible :kipu_insurance_id, :payer_name,
                  # :payer_synonym, :api_payer_id,
                  # :provider_id, :type  - need to add to migration


  def self.import
      update_folder = 'db/update_files/'
      import_file   = Rails.root.join(update_folder,'payers_test.json')
      records       = JSON.parse(File.read(import_file))

      fields = {}

      records.each do |payer|
        payer['PayerSynonyms'].each do |synonym|
          fields[:kipu_insurance_id] = payer['Id']
          fields[:api_payer_id]      = payer['ApiPayerId']
          fields[:payer_name]        = payer['HealthPlanName']
          fields[:payer_synonym]     = synonym['Name']
          # puts fields
          Payer.create(fields)
        end
      end
      puts 'Import Complete'



  end
end

app/models/payers_list.rb
class PayersList < ActiveRecord::Base

  # attr_accessible :kipu_insurance_id, :payer_name,
                  # :payer_synonym, :api_payer_id,
                  # :provider_id, :type  - need to add to migration


  def self.import
      update_folder = 'db/update_files/'
      import_file   = Rails.root.join(update_folder,'payers_2016-03-10.json')
      records       = JSON.parse(File.read(import_file))

      fields = {}

      records.each do |payer|
        payer['PayerSynonyms'].each do |synonym|
          fields[:kipu_insurance_id] = payer['Id']
          fields[:api_payer_id]      = payer['ApiPayerId']
          fields[:payer_name]        = payer['HealthPlanName']
          fields[:payer_synonym]     = synonym['Name']
          # puts fields
          PayersList.create(fields)
        end
      end
      puts 'Import Complete'



  end
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :location
  belongs_to :role
  belongs_to :manager, class_name: "Person", foreign_key: :manager_id
  has_many :employees, class_name: "Person", foreign_key: :manager_id

  def self.in_region(region)
    joins(:location).merge( Location.joins(:region).
                     where(regions: {name: region}) )
  end

  def self.alphabetically_by_region_and_location
    joins(:location).merge( Location.joins(:region)).
            order('regions.name, locations.name, people.name' )
  end
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :locations

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_one :collaborate_md_interface,  dependent: :destroy

  # attr_accessible  :company_name,  :vendor_status,  :vendor_type,
  # only necessary in Rails 3 - like Healthmatters.  'whitelis'


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :all_tasks, only: [:index, :create]
  respond_to :html, :js

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
  end

  private

    def all_tasks
      @tasks = Task.all
    end

    def task_params
      params.require(:task).permit(:description, :deadline)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @user = User.new #placed here for Ajax tutorial from Rails guide
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|

      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }

        format.js {}

        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carros_helper.rb
module CarrosHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/payers_helper.rb
module PayersHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tasks/_form.html.erb
<%= simple_form_for(@task, remote: true) do |f| %>
  <%= f.input :description %>
  <%= f.input :deadline %>
  <%= f.button :submit %>
<% end %>

app/views/tasks/create.js.erb
$('#tasks').html("<%= j (render @tasks) %>");
$('#task-form').slideup(350);

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Deadline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= task.deadline %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path, remote: true %>
<div id="task-form" style="display:none;"></div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350)

app/views/tasks/new_index.html.erb
<div class="row">
  <div class="col-md-5 col-md-offset-1">
    <h2>Tasks</h2>
  </div>

  <div class="col-md-2 col-md-offset-4">
    <%= link_to new_task_path, remote: true do  %>
      <button class="btn btn-default">New</button>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-2" id="task-form" style="display:none;"></div>
</div>

<div class="row">
  <div class="col-md-7 col-md-offset-1" id="tasks"><%= render @tasks %></div>
</div>

app/views/tasks/old_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Deadline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= task.deadline %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path, remote: true %>
<div id="task-form" style="display:none;"></div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li><%= user.name %></li>

app/views/users/create.js.erb
$("<%= j(render @user) %>").appendTo("#users");
console.log($("#users").length);

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<!-- <h1>Users</h1> -->

<!-- <table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
commented out all this which the scaffold generator made.  Ajax Tutorial from Rails guide.  10/08/2016
-->
<h1>Users</h1>

<ul id="users">
  <%= render @users %> <!-- This looks for a partial named _user.html.erb -->
</ul>

<br>

<%= form_for(@user, remote: true) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

<br>

<!-- <%= link_to 'New User', new_user_path %> -->

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>