config/routes.rb
Rails.application.routes.draw do
  resources :carros
  resources :users
  resources :addresses
  resources :actors
  get 'actors/index'

  get 'actors/show'

  get 'actors/create'

  get 'actors/update'

  get 'actors/destroy'

  resources :movies

  resources :movies
  root 'payers#index'
  resources :payers

  resources :tasks

  get 'verification_autocomplete/.:format' => 'routes#test_action'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/carro.rb
class Carro < ActiveRecord::Base
end

app/models/interface_log.rb
class InterfaceLog < ActiveRecord::Base
    belongs_to :patient_master, autosave: true

  # attr_accessible :response_message, #formerly known as :content_file
  #                 :response_code,
  #                 :response_timestamp,
  #                 :vendor_account,
  #                 :vendor_id,
  #                 :vendor_name,
  #                 :vendor_type,
  #                 :patient_master_id,
  #                 :patient_master_uuid,
  #                 :user_full_name,
  #                 :user_id,
  #                 :log   # Paperclip

  def log_entry(log={})

    self.patient_master_id =    log[:p_master_id]
    self.response_message  =    log[:r_message]
    self.response_code =        log[:r_code]
    self.response_timestamp =   log[:r_timestamp]
    self.vendor_account =       log[:v_account]
    self.vendor_id =            log[:v_id]
    self.vendor_name =          log[:v_name]
    self.patient_master_uuid =  log[:p_master_uuid]
    self.user_full_name =       log[:u_full_name]
    self.user_id =              log[:u_id]

    puts log
    self.save
  end
end

=begin
{
 :patient_master_id=>10,
 :response_message=>"El mensajito",
 :response_code=>"201",
 :response_timestamp=>"20160511",
 :vendor_account=>"909090909",
 :vendor_id=>"223344",
 :vendor_name=>"CMD Orlando",
 :vendor_type=>"collaborate_md",
 :patient_master_uuid=>"e02aa3de-1f3b-4083-9f26-5532522b5d81",
 :user_full_name=>"Angel Huezo",
 :user_id=>"1"
 }

 {
 :p_master_id=>10, :r_message=>"El mensajito", :r_code=>"201", :r_timestamp=>"20160511",
 :v_account=>"909090909", :v_id=>"223344", :v_name=>"CMD Orlando", :v_type=>"collaborate_md",
 :p_master_uuid=>"e02aa3de-1f3b-4083-9f26-5532522b5d81", :u_full_name=>"Angel Huezo", :u_id=>"1"
 }
=end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :region
  has_many :people

  def self.in_region(region)

    # joins(:region).merge(Region.where('regions.name = ?', region))
    joins(:region).where(regions: {name: region}) #same as above, but clearer

  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/models/payer.rb
class Payer < ActiveRecord::Base
   # attr_accessible :kipu_insurance_id, :payer_name,
                  # :payer_synonym, :api_payer_id,
                  # :provider_id, :type  - need to add to migration


  def self.import
      update_folder = 'db/update_files/'
      import_file   = Rails.root.join(update_folder,'payers_test.json')
      records       = JSON.parse(File.read(import_file))

      fields = {}

      records.each do |payer|
        payer['PayerSynonyms'].each do |synonym|
          fields[:kipu_insurance_id] = payer['Id']
          fields[:api_payer_id]      = payer['ApiPayerId']
          fields[:payer_name]        = payer['HealthPlanName']
          fields[:payer_synonym]     = synonym['Name']
          # puts fields
          Payer.create(fields)
        end
      end
      puts 'Import Complete'



  end
end

app/models/payers_list.rb
class PayersList < ActiveRecord::Base

  # attr_accessible :kipu_insurance_id, :payer_name,
                  # :payer_synonym, :api_payer_id,
                  # :provider_id, :type  - need to add to migration


  def self.import
      update_folder = 'db/update_files/'
      import_file   = Rails.root.join(update_folder,'payers_2016-03-10.json')
      records       = JSON.parse(File.read(import_file))

      fields = {}

      records.each do |payer|
        payer['PayerSynonyms'].each do |synonym|
          fields[:kipu_insurance_id] = payer['Id']
          fields[:api_payer_id]      = payer['ApiPayerId']
          fields[:payer_name]        = payer['HealthPlanName']
          fields[:payer_synonym]     = synonym['Name']
          # puts fields
          PayersList.create(fields)
        end
      end
      puts 'Import Complete'



  end
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :location
  belongs_to :role
  belongs_to :manager, class_name: "Person", foreign_key: :manager_id
  has_many :employees, class_name: "Person", foreign_key: :manager_id

  def self.in_region(region)
    joins(:location).merge( Location.joins(:region).
                     where(regions: {name: region}) )
  end

  def self.alphabetically_by_region_and_location
    joins(:location).merge( Location.joins(:region)).
            order('regions.name, locations.name, people.name' )
  end
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :locations

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_one :collaborate_md_interface,  dependent: :destroy

  # attr_accessible  :company_name,  :vendor_status,  :vendor_type,
  # only necessary in Rails 3 - like Healthmatters.  'whitelis'


end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:street, :city, :state, :zipcode)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carros_helper.rb
module CarrosHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/payers_helper.rb
module PayersHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode, maxlength: "15" %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Zipcode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.street %></td>
        <td><%= address.city %></td>
        <td><%= address.state %></td>
        <td><%= address.zipcode %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street:</strong>
  <%= @address.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @address.zipcode %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>